# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import csv 
import time 
import datetime 
import optimizer
from models import Tire
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self) -> None:
        self.time_complete = None
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 761, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.Model = QtWidgets.QWidget()
        self.Model.setObjectName("Model")
        self.frame = QtWidgets.QFrame(self.Model)
        self.frame.setGeometry(QtCore.QRect(10, -10, 731, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 421, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label_6 = QtWidgets.QLabel(self.Home)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 411, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/variables.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.Home)
        self.Dm_page = QtWidgets.QWidget()
        self.Dm_page.setObjectName("Dm_page")
        self.label = QtWidgets.QLabel(self.Dm_page)
        self.label.setGeometry(QtCore.QRect(130, 90, 60, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.Dm_page)
        self.Df_page = QtWidgets.QWidget()
        self.Df_page.setObjectName("Df_page")
        self.label_2 = QtWidgets.QLabel(self.Df_page)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 60, 16))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.Df_page)
        self.D_page = QtWidgets.QWidget()
        self.D_page.setObjectName("D_page")
        self.label_3 = QtWidgets.QLabel(self.D_page)
        self.label_3.setGeometry(QtCore.QRect(220, 150, 60, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.D_page)
        self.Wm_page = QtWidgets.QWidget()
        self.Wm_page.setObjectName("Wm_page")
        self.label_4 = QtWidgets.QLabel(self.Wm_page)
        self.label_4.setGeometry(QtCore.QRect(280, 170, 60, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.Wm_page)
        self.N_page = QtWidgets.QWidget()
        self.N_page.setObjectName("N_page")
        self.label_5 = QtWidgets.QLabel(self.N_page)
        self.label_5.setGeometry(QtCore.QRect(280, 160, 60, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.N_page)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(430, 20, 261, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(15, 33, 221, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_8.setGeometry(QtCore.QRect(19, 299, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.textBrowser_model_2 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_model_2.setGeometry(QtCore.QRect(10, 30, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textBrowser_model_2.setFont(font)
        self.textBrowser_model_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_model_2.setObjectName("textBrowser_model_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_12.setGeometry(QtCore.QRect(430, 190, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.textBrowser_model = QtWidgets.QTextBrowser(self.groupBox_12)
        self.textBrowser_model.setGeometry(QtCore.QRect(10, 30, 241, 181))
        self.textBrowser_model.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_model.setObjectName("textBrowser_model")
        self.groupBox_12.raise_()
        self.stackedWidget.raise_()
        self.groupBox.raise_()
        self.groupBox_8.raise_()
        self.tabWidget.addTab(self.Model, "")
        self.Optimizer = QtWidgets.QWidget()
        self.Optimizer.setObjectName("Optimizer")
        self.groupBox_9 = QtWidgets.QGroupBox(self.Optimizer)
        self.groupBox_9.setGeometry(QtCore.QRect(400, 220, 351, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_9)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 30, 331, 171))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(331, 0))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(4, 2, item)
        self.groupBox_10 = QtWidgets.QGroupBox(self.Optimizer)
        self.groupBox_10.setGeometry(QtCore.QRect(400, 10, 351, 205))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_10)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.LmReq = QtWidgets.QSpinBox(self.groupBox_10)
        self.LmReq.setMinimum(2000)
        self.LmReq.setMaximum(89000)
        self.LmReq.setSingleStep(1000)
        self.LmReq.setProperty("value", 36000)
        self.LmReq.setDisplayIntegerBase(10)
        self.LmReq.setObjectName("LmReq")
        self.gridLayout.addWidget(self.LmReq, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.SiReq = QtWidgets.QSpinBox(self.groupBox_10)
        self.SiReq.setMaximum(350)
        self.SiReq.setSingleStep(10)
        self.SiReq.setProperty("value", 200)
        self.SiReq.setObjectName("SiReq")
        self.gridLayout.addWidget(self.SiReq, 1, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox.setMinimum(0.5)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 3, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_2.setMinimum(0.5)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.05)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 4, 1, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Optimizer)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 371, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 351, 341))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setTabStopWidth(79)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.Optimizer)
        self.pushButton.setGeometry(QtCore.QRect(110, 400, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Optimizer, "")
        self.Output = QtWidgets.QWidget()
        self.Output.setObjectName("Output")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Output)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 251, 431))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 231, 391))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.Output)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 340, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.Output)
        self.groupBox_11.setGeometry(QtCore.QRect(280, 10, 471, 301))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_11)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 30, 451, 261))
        self.tableWidget_3.setMinimumSize(QtCore.QSize(331, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget.addTab(self.Output, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tire Optimizer"))
        self.label.setText(_translate("MainWindow", "Dm"))
        self.label_2.setText(_translate("MainWindow", "Df"))
        self.label_3.setText(_translate("MainWindow", "D"))
        self.label_4.setText(_translate("MainWindow", "Wm"))
        self.label_5.setText(_translate("MainWindow", "N"))
        self.groupBox.setTitle(_translate("MainWindow", "Design Variables"))
        self.label_12.setText(_translate("MainWindow", "Dm: mean tire diameter"))
        self.label_13.setText(_translate("MainWindow", "DF: outer wheel flange diameter"))
        self.label_14.setText(_translate("MainWindow", "D: rim diameter"))
        self.label_15.setText(_translate("MainWindow", "Wm: mean overall tire width"))
        self.label_16.setText(_translate("MainWindow", "N: ply rating"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Terms of Service"))
        self.textBrowser_model_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</span></p></body></html>"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Background"))
        self.textBrowser_model.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Todo: fill background </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Model), _translate("MainWindow", "Model"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Optimization Scope"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Dm"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "DF"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "D"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wm"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "N"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lower Bound"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Upper Bound"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial Value *"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "56"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "33"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(4, 1)
        item.setText(_translate("MainWindow", "38"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.groupBox_10.setTitle(_translate("MainWindow", "Optimization Parameter"))
        self.label_7.setText(_translate("MainWindow", "Loading Capacity [lbs]"))
        self.label_8.setText(_translate("MainWindow", "Speed Index [mph]"))
        self.label_9.setText(_translate("MainWindow", "Cord Material"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Aramid (Kevlar 29)"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Cotton"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Polyester"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Rayon"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Polyamid Nylon"))
        self.label_10.setText(_translate("MainWindow", "Aspect Ratio (min, max)"))
        self.label_11.setText(_translate("MainWindow", "Tolerance"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "1e-4"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1e-3"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "1e-4"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "1e-5"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "1e-6"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Optimizer Instruction"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Todo: fill optimizer instructions <br /><br /><br />* Leave blank or enter 0 if using mean value between bounds. </span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Run Optimizer"))
        self.pushButton.clicked.connect(self.run_optimization)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Optimizer), _translate("MainWindow", "Optimizer"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Optimizer Description"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please run optimizer in the \"Optimizer\" tab </p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Save to CSV"))
        self.pushButton_2.clicked.connect(self.save_csv)
        self.groupBox_11.setTitle(_translate("MainWindow", "Optimization Output"))
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Dm"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "DF"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "D"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wm"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "N"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Loading Capacity [lbs]"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Inflation Pressure [psi]"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Est. Tire Mass [kg]"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Optimizer"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Michelin"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Goodyear"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Output), _translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
    
    def show_warning(self, message): 
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("Warning")
        msg.setInformativeText(message)
        msg.setWindowTitle("Warning")
        msg.exec_()
        
    def show_complete(self, message): 
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("Complete")
        msg.setInformativeText(message)
        msg.setWindowTitle("Complete")
        msg.exec_()
    
    def run_optimization(self): 
        def retrieve_tire_data(tire: Tire): 
            output = {} 
            output['Dm'] = tire.Dm
            output['DF'] = tire.DF
            output['D'] = tire.D
            output['Wm'] = tire.Wm
            output['PR'] = tire.PR
            output['Lm'] = tire.max_load_capacity()
            output['IP'] = tire.inflation_pressure() 
            output['Mass'] = tire.estimated_tire_mass()
            return output 
            
        # Receive user inputs 
        self.scopes = {}
        for i, var in enumerate(['Dm', 'DF', 'D', 'Wm', 'PR']): 
            self.scopes[var] = (
                float(self.tableWidget_2.item(i, 0).text()), 
                float(self.tableWidget_2.item(i, 1).text()), 
                float(self.tableWidget_2.item(i, 2).text()) 
            )
        
        self.Lm_req = float(self.LmReq.text())
        self.I_speed = float(self.SiReq.text()) 
        self.tolerance = float(self.comboBox_4.itemText(self.comboBox_4.currentIndex()))
        
        self.cord_brake_load = 0 
        self.cord_material = self.comboBox_3.currentIndex()
        if self.cord_material == 0: # Aramid (Kevlar 29)
            self.cord_brake_load = 338.0 
        elif self.cord_material == 1: # Cotton 
            self.cord_brake_load == 42.0 
        elif self.cord_material == 2: # Polyester
            self.cord_brake_load == 228.0 
        elif self.cord_material == 3: # Rayon
            self.cord_brake_load == 115.0 
        elif self.cord_material == 4: # Polyamid Nylon  
            self.cord_brake_load == 175.0 
        self.cord_material = self.comboBox_3.itemText(self.cord_material) # store material name 
        
        self.aspect_ratio = [
            float(self.doubleSpinBox.text()), float(self.doubleSpinBox_2.text())
        ] # (min, max)
        if self.aspect_ratio[0] >= self.aspect_ratio[1]: 
            self.show_warning("Aspect ratio min must be smaller than max!")
            return 
        
        # Run optimizer 
        st = time.time() 
        self.opt_tire = optimizer.gradients_opt(
            self.Lm_req * 1.07, self.I_speed, self.cord_brake_load, self.scopes, self.aspect_ratio, self.tolerance
        )
        self.michelin_tire = optimizer.search_databook(self.Lm_req * 1.07, self.I_speed, source='michelin')
        self.goodyear_tire = optimizer.search_databook(self.Lm_req * 1.07, self.I_speed, source='goodyear')
        self.time_elapsed = time.time() - st
        self.time_complete = datetime.datetime.now()
        
        # Print summary of input 
        input_summary = f"""<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
    p, li {{ white-space: pre-wrap; }}
</style></head><body style=" font-family:'.AppleSystemUIFont'; font-size:14pt; font-weight:400; font-style:normal;">
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><strong>Optimization input:</strong></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Loading capacity [lbs]: {self.Lm_req}</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Speed index [mph]: {self.I_speed}</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Cord material: {self.cord_material}</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Cord brake strength [N]: {self.cord_brake_load}</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Tolerance: {self.tolerance}</p>
<br /><p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><strong>Optimization scope:</strong></p>
        """
        for var in ['Dm', 'DF', 'D', 'Wm', 'PR']: 
            var_display = var if var != "PR" else "N"
            init = self.scopes[var][2] if self.scopes[var][2] else (self.scopes[var][0] + self.scopes[var][1]) / 2
            input_summary += f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{var_display}: [{self.scopes[var][0]}, {self.scopes[var][1]}] (init: {init})</p>"
        input_summary += f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Aspect ratio: [{self.aspect_ratio[0]}, {self.aspect_ratio[1]}]</p><br />"
        
        input_summary += f"""<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><strong>Optimization details:</strong></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Time elapsed: {round(self.time_elapsed, 4)} seconds</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Time completed: {self.time_complete.strftime("%Y-%m-%d %H:%M:%S")}</p>
        """
        
        input_summary += "</body></html>"
        self.textBrowser_2.setHtml(input_summary)
        
        # Print output 
        if self.opt_tire: 
            output = retrieve_tire_data(self.opt_tire)
            for i, var in enumerate(['Dm', 'DF', 'D', 'Wm', 'PR', "Lm", "IP", "Mass"]): 
                item = QtWidgets.QTableWidgetItem()
                item.setText(str(round(output[var], 2)))
                self.tableWidget_3.setItem(i, 0, item)
        else: 
            for i in range(8):
                item = QtWidgets.QTableWidgetItem()
                item.setText("N/A")
                self.tableWidget_3.setItem(i, 0, item)
                
        if self.michelin_tire: 
            output = retrieve_tire_data(self.michelin_tire)
            for i, var in enumerate(['Dm', 'DF', 'D', 'Wm', 'PR', "Lm", "IP", "Mass"]): 
                item = QtWidgets.QTableWidgetItem()
                item.setText(str(round(output[var], 2)))
                self.tableWidget_3.setItem(i, 1, item)
        else: 
            for i in range(8):
                item = QtWidgets.QTableWidgetItem()
                item.setText("N/A")
                self.tableWidget_3.setItem(i, 1, item)
        
        if self.goodyear_tire: 
            output = retrieve_tire_data(self.goodyear_tire)
            for i, var in enumerate(['Dm', 'DF', 'D', 'Wm', 'PR', "Lm", "IP", "Mass"]): 
                item = QtWidgets.QTableWidgetItem()
                item.setText(str(round(output[var], 2)))
                self.tableWidget_3.setItem(i, 2, item)
        else: 
            for i in range(8):
                item = QtWidgets.QTableWidgetItem()
                item.setText("N/A")
                self.tableWidget_3.setItem(i, 2, item)

        # Redirect to Output page
        self.tabWidget.setCurrentIndex(2)
        
    def save_csv(self): 
        if not self.time_complete: 
            self.show_warning("Please run optimizer before saving results in CSV.")
            return 
        
        with open("opt_output_{}.csv".format(self.time_complete.strftime("%Y-%m-%d_%H-%M-%S")), "w") as csv_file: 
            csv_writer = csv.writer(csv_file)
            
            csv_writer.writerow(['Optimization details'])
            csv_writer.writerow(['Time completed', self.time_complete.strftime("%Y-%m-%d %H:%M:%S")])
            csv_writer.writerow(['Time elapsed', self.time_elapsed, 'seconds'])
            csv_writer.writerow(['Optimizer', 'SLSQP'])
            csv_writer.writerow(['Success', self.opt_tire != None])
            csv_writer.writerow([])
            
            csv_writer.writerow(['Optimization inputs'])
            csv_writer.writerow(["Loading capacity", self.Lm_req, "lbs"])
            csv_writer.writerow(["Speed index", self.I_speed, "mph"])
            csv_writer.writerow(["Cord material", self.cord_material])
            csv_writer.writerow(["Cord brake strength", self.cord_brake_load, "N"])
            csv_writer.writerow(["Tolerance of termination", self.tolerance])
            csv_writer.writerow([])
            
            csv_writer.writerow(['Optimization scope'])
            csv_writer.writerow(['Variable', 'Min', 'Max', 'Initial'])
            for var in ['Dm', 'DF', 'D', 'Wm', 'PR']: 
                var_display = var + " [in]" if var != "PR" else "N"
                init = self.scopes[var][2] if self.scopes[var][2] else (self.scopes[var][0] + self.scopes[var][1]) / 2
                csv_writer.writerow([var_display, self.scopes[var][0], self.scopes[var][1], init])
            csv_writer.writerow(['Aspect ratio'] + self.aspect_ratio)
            csv_writer.writerow([])
            
            csv_writer.writerow(['Optimization results'])
            csv_writer.writerow(['', 'Optimizer', 'Michelin', 'Goodyear'])
            for i in range(8): 
                row = [self.tableWidget_3.verticalHeaderItem(i).text()] 
                for j in range(3): 
                    row.append(self.tableWidget_3.item(i, j).text())
                csv_writer.writerow(row)

        self.show_complete("CSV exported successfully!")
                

if __name__ == "__main__": 
    import sys 
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() 
    ui = Ui_MainWindow() 
    ui.setupUi(MainWindow)
    MainWindow.show() 
    sys.exit(app.exec_())